# ZSH
DISABLE_AUTO_UPDATE=true
export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="pygmalion-custom"
plugins=(git git-prompt gcloud gitfast colorize zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
export EDITOR='vim'
autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do compinit; done
compinit -C

# Syntax Highlighting
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=green,bold'

# FZF Fuzzy Finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Functions
function r() { grep "$1" ${@:2} -I -R . }
function mkcd() { mkdir -p "$@" && cd "$_"; }

# Aliases
alias f='fd'
alias cd..='cd ..'
alias mv='mv -i'
alias jn='jupyter notebook --NotebookApp.token=token123 --no-browser'
alias vim='nvim'
alias sed='sed -E'
alias xbrew='arch -x86_64 /usr/local/bin/brew'
alias mkdir="mkdir -p"
alias df="df -h"
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Determine size of a file or total size of a directory
function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* ./*;
	fi;
}

# Git branch completion 
zstyle ':completion:*:*:git:*' script ~/.oh-my-zsh/plugins/gitfast/git-completion.bash

export PATH="/opt/homebrew/bin:$PATH"
source ~/.zshrc.profile
